//! FST file writing

use std::path::Path;

use wellen::SignalRef;

use crate::error::{Error, Result};
use crate::filter::SignalSelection;
use crate::waveform_legacy::WaveformFile;

/// Progress information during FST writing
#[derive(Debug, Clone)]
pub struct WriteProgress {
    pub signals_written: usize,
    pub signals_total: usize,
    pub current_signal_name: String,
}

impl WriteProgress {
    /// Get progress as a percentage (0.0 to 1.0)
    pub fn percentage(&self) -> f64 {
        if self.signals_total == 0 {
            0.0
        } else {
            self.signals_written as f64 / self.signals_total as f64
        }
    }
}

/// Configuration for FST output
#[derive(Debug, Clone)]
pub struct FstWriterConfig {
    pub comment: Option<String>,
    pub timescale: Option<String>,
}

impl Default for FstWriterConfig {
    fn default() -> Self {
        Self {
            comment: Some("Generated by fstty".to_string()),
            timescale: None,
        }
    }
}

/// Handles writing filtered waveforms to FST format
pub struct FilteredFstWriter {
    _config: FstWriterConfig,
}

impl FilteredFstWriter {
    /// Create a new writer with the given configuration
    pub fn new(config: FstWriterConfig) -> Self {
        Self { _config: config }
    }

    /// Write selected signals to a new FST file
    ///
    /// This is a placeholder implementation - full implementation requires
    /// mapping wellen signal data to fstapi format.
    pub fn write<F>(
        &self,
        source: &mut WaveformFile,
        selection: &SignalSelection,
        output_path: impl AsRef<Path>,
        mut progress_callback: F,
    ) -> Result<()>
    where
        F: FnMut(WriteProgress),
    {
        let output_path = output_path.as_ref();
        tracing::info!("Writing filtered FST to: {}", output_path.display());

        // Collect signals to write
        let signals: Vec<SignalRef> = selection.resolve(source.hierarchy()).collect();
        let total = signals.len();

        if total == 0 {
            return Err(Error::FstWrite("No signals selected for writing".to_string()));
        }

        tracing::info!("Writing {} signals to FST", total);

        // TODO: Implement actual FST writing using fstapi
        // This requires:
        // 1. Create fstapi::Writer
        // 2. Set up timescale from source
        // 3. Create scope hierarchy in output
        // 4. Create variables for each signal
        // 5. Load signal values and emit value changes
        // 6. Handle time progression

        // For now, report progress as if we're writing
        for (i, _signal_ref) in signals.iter().enumerate() {
            progress_callback(WriteProgress {
                signals_written: i,
                signals_total: total,
                current_signal_name: format!("signal_{}", i),
            });
        }

        progress_callback(WriteProgress {
            signals_written: total,
            signals_total: total,
            current_signal_name: String::new(),
        });

        // Placeholder: actual implementation would write the file here
        Err(Error::FstWrite(
            "FST writing not yet implemented - requires fstapi integration".to_string(),
        ))
    }
}

impl Default for FilteredFstWriter {
    fn default() -> Self {
        Self::new(FstWriterConfig::default())
    }
}
